# Predefined valid values
VALID_GENDER_CATEGORIES = [
    "Men", 
    "Women",
]
VALID_CATEGORIES = [
    'Clothing',
    'Shoes',
    'Accessories',
    'Bags',
    'Jewelry',
    'Clothing',
    'Shoes',
    'Accessories',
    'Bags',
    'Jewelry',
]
VALID_SUBCATEGORIES = [
    'T-Shirts',
    'Shirts',
    'Jeans',
    'Pants',
    'Shorts',
    'Suits',
    'Knitwear',
    'Coats',
    'Jackets',
    'Activewear',
    'Beachwear & Swimwear',
    'Nightwear & Sleepwear',
    'Underwear',
    'Sneakers',
    'Boots',
    'Lace-Ups',
    'Slip-On Shoes',
    'Sandals & Slides',
    'Sandals & Slides',
    'Sandals & Slides',
    'Sandals & Slides',
    'Dresses',
    'T-Shirts',
    'Tops',
    'Knitwear',
    'Jeans',
    'Pants',
    'Shorts',
    'Skirts',
    'Jumpsuits & Rompers',
    'Suits',
    'Coats',
    'Jackets',
    'Activewear',
    'Beachwear & Swimwear Outfits',
    'Lingerie',
    'Nightwear & Sleepwear',
    'Hosiery',
    'Underwear',
    'Sneakers',
    'Heels',
    'Boots',
    'Flats',
    'Sandals & Slides',
    'Slip-On Shoes',
    'Belts',
    'Hats',
    'Scarves and Mufflers',
    'Gloves',
    'Face Masks',
    'Sunglasses',
    'Headbands and Hair Accessories',
    'Ties',
    'Umbrellas',
    'Watches',
    'Wallets and Cardholders',
    'Phone Cases',
    'Tote Bags',
    'Shoulder Bags',
    'Crossbody Bags',
    'Clutches and Evening Bags',
    'Satchel Bags and Purses',
    'Top-Handle Bags',
    'Hobo Bags and Purses',
    'Duffel Bags and Weekend Bags',
    'Messenger Bags',
    'Backpacks',
    'Belt Bags',
    'Briefcases and Work Bags',
    'Bucket Bags and Bucket Purses',
    'Makeup Bags and Cosmetic Cases',
    'Luggage',
    'Pouches and Wristlets',
    'Necklaces',
    'Bracelets',
    'Rings',
    'Earrings and Ear Cuffs',
    'Brooches',
]
VALID_SUBSUBCATEGORIES = [
    'Short Sleeve T-Shirts',
    'Long-Sleeve T-Shirts',
    'Polo Shirts',
    'Sleeveless T-Shirts',
    'Casual Shirts and Button-Up Shirts',
    'Formal Shirts',
    'Slim Jeans',
    'Skinny Jeans',
    'Straight-Leg Jeans',
    'Tapered Jeans',
    'Relaxed and Loose-Fit Jeans',
    'Bootcut Jeans',
    'Casual Pants',
    'Formal Pants',
    'Casual Shorts',
    'Bermuda Shorts',
    'Cargo Shorts',
    'Formal Shorts',
    'Two-Piece Suits',
    'Three-Piece Suits',
    'Tuxedos and Evening Suits',
    'Crew Neck Sweaters',
    'V-Neck Sweaters',
    'Cardigans',
    'Zipped Sweaters',
    'Turtlenecks',
    'Sleeveless Sweaters',
    'Trench Coats',
    'Long Coats and Winter Coats',
    'Short Coats',
    'Parka Coats',
    'Casual Jackets',
    'Leather Jackets',
    'Down and Padded Jackets',
    'Blazers',
    'Waistcoats and Gilets',
    'Hoodies',
    'Sweatshirts',
    'Sweatpants',
    'Sweatshorts',
    'Tracksuits and Sweat Suits',
    'Swim Trunks and Swim Shorts',
    'Boardshorts',
    'Beach Towels',
    'Pajamas',
    'Robes and Bathrobes',
    'Boxers',
    'Boxer Briefs',
    'Socks',
    'Undershirts and Vests',
    'High-Top Sneakers',
    'Low-Top Sneakers',
    'Casual Boots',
    'Chukka Boots and Desert Boots',
    'Formal and Smart Boots',
    'Wellington and Rain Boots',
    'Oxford Shoes',
    'Derby Shoes',
    'Brogues',
    'Loafers',
    'Monk Shoes',
    'Boat and Deck Shoes',
    'Espadrilles',
    'Slippers',
    'Leather Sandals',
    'Flip-Flops',
    'Belts',
    'Hats',
    'Sunglasses',
    'Scarves and Mufflers',
    'Gloves',
    'Face Masks',
    'Ties',
    'Cufflinks',
    'Wallets and Cardholders',
    'Watches',
    'Backpacks',
    'Messenger Bags',
    'Tote Bags',
    'Briefcases and Laptop Bags',
    'Gym Bags and Duffel Bags',
    'Weekender Bags',
    'Belt Bags and Fanny Packs',
    'Luggage',
    'Cases',
    'Pouches and Wristlets',
    'Toiletry Bags and Wash Bags',
    'Rings',
    'Necklaces',
    'Bracelets',
    'Earrings and Ear Cuffs',
    'Brooches',
    'Casual and Day Dresses',
    'Cocktail and Party Dresses',
    'Formal Dresses and Evening Gowns',
    'Maxi Dresses',
    'Mini and Short Dresses',
    'Short Sleeve T-Shirts',
    'Long-Sleeve T-Shirts',
    'Polo Shirts',
    'Sleeveless T-Shirts',
    'Blouses',
    'Long-Sleeved Tops',
    'Shirts',
    'Short-Sleeve Tops',
    'Sleeveless and Tank Tops',
    'Sweaters and Pullovers',
    'Cardigans',
    'Crew Neck Sweaters',
    'V-Neck Sweaters',
    'Turtlenecks',
    'Zipped Sweaters',
    'Ponchos and Poncho Dresses',
    'Sleeveless Sweaters',
    'Skinny Jeans',
    'Straight-Leg Jeans',
    'Wide-Leg Jeans',
    'Bootcut Jeans',
    'Capri and Cropped Jeans',
    'Flare and Bell Bottom Jeans',
    'Full-Length Pants',
    'Capri and Cropped Pants',
    'Skinny Pants',
    'Wide-Leg and Palazzo Pants',
    'Straight-Leg Pants',
    'Harem Pants',
    'Casual Pants',
    'Cargo Pants',
    'Leggings',
    'Casual Shorts',
    'Knee-Length Shorts',
    'Mini Shorts',
    'Cargo Shorts',
    'Jean and Denim Shorts',
    'Formal Shorts',
    'Mini Skirts',
    'Mid-Length Skirts',
    'Knee-Length Skirts',
    'Maxi Skirts',
    'Full-Length Jumpsuits and Rompers',
    'Playsuits',
    'Pant Suits',
    'Skirt Suits',
    'Two-Piece Suits',
    'Long Coats and Winter Coats',
    'Parka Coats',
    'Trench Coats',
    'Short Coats',
    'Capes',
    'Fur Coats',
    'Blazers, Sport Coats, and Suit Jackets',
    'Casual Jackets',
    'Leather Jackets',
    'Jean and Denim Jackets',
    'Fur Jackets',
    'Padded and Down Jackets',
    'Waistcoats and Gilets',
    'Hoodies',
    'Sweatshirts',
    'Track Pants and Sweatpants',
    'Sweatshorts',
    'Tracksuits and Sweat Suits',
    'Bikinis',
    'One-Piece Swimsuits and Bathing Suits',
    'Cover-Ups and Kaftans',
    'Sarongs and Sarong Wraps',
    'Swim Trunks and Swim Shorts',
    'Beach Towels',
    'Bras',
    'Bodysuits',
    'Corsets and Bustier Tops',
    'Camisoles',
    'Panties and Underwear',
    'Lingerie and Panty Sets',
    'Nightgowns and Sleepshirts',
    'Pajamas',
    'Robes, Robe Dresses, and Bathrobes',
    'Socks',
    'Tights and Pantyhose',
    'Stockings',
    'Socks',
    'High-Top Sneakers',
    'Low-Top Sneakers',
    'Stilettos and High Heels',
    'Pump Shoes',
    'Platform Heels',
    'Mule Shoes',
    'Sandal Heels',
    'Wedge Shoes and Pumps',
    'Ankle Boots',
    'Knee-High Boots',
    'Mid-Calf Boots',
    'Over-the-Knee Boots',
    'Casual Boots',
    'Wedge Boots',
    'Heel and High Heel Boots',
    'Wellington and Rain Boots',
    'Ballet Flats and Ballerina Shoes',
    'Espadrille Shoes and Sandals',
    'Loafers and Moccasins',
    'Flat Sandals',
    'Leather Sandals',
    'Flip-Flops',
    'Loafers and Moccasins',
    'Slippers',
]
VALID_FITS = [
    'Slim Fit',
    'Regular Fit',
    'Relaxed Fit',
    'Oversized Fit',
    'Athletic Fit',
    'Boxy Fit',
    'Tailored Fit',
    'Flowy Fit',
    'Crop Fit',
    'Muscle Fit',
    'Fitted',
    'Curved Hem Fit',
    'Skinny Fit',
    'Slim Fit',
    'Straight Fit',
    'Relaxed Fit',
    'Loose Fit',
    'Bootcut Fit',
    'Wide Leg Fit',
    'Tapered Fit',
    'High-Waisted Fit',
    'Mid-Rise Fit',
    'Low-Rise Fit',
    'Paperbag Fit',
    'Cargo Fit',
    'Cropped Fit',
    'Boyfriend Fit',
    'Mom Fit',
    'Flared Fit',
    'Carrot Fit',
    'A-Line Fit',
    'Bodycon Fit',
    'Shift Fit',
    'Wrap Fit',
    'Empire Fit',
    'Fit and Flare',
    'Maxi Fit',
    'Midi Fit',
    'Mini Fit',
    'Tailored Fit',
    'Regular Fit',
    'Relaxed Fit',
    'Oversized Fit',
    'Slim Fit',
    'Cropped Fit',
    'Parka Fit',
    'Trench Fit',
    'Bomber Fit',
    'Duster Fit',
    'Puffer Fit',
]
VALID_COLORS = [
    'Air Force blue',
    'Alice blue',
    'Alizarin crimson',
    'Almond',
    'Amaranth',
    'Amber',
    'American rose',
    'Amethyst',
    'Android Green',
    'Anti-flash white',
    'Antique brass',
    'Antique fuchsia',
    'Antique white',
    'Ao',
    'Apple green',
    'Apricot',
    'Aqua',
    'Aquamarine',
    'Army green',
    'Arylide yellow',
    'Ash grey',
    'Asparagus',
    'Atomic tangerine',
    'Auburn',
    'Aureolin',
    'AuroMetalSaurus',
    'Awesome',
    'Azure',
    'Azure mist/web',
    'Baby blue',
    'Baby blue eyes',
    'Baby pink',
    'Ball Blue',
    'Banana Mania',
    'Banana yellow',
    'Battleship grey',
    'Bazaar',
    'Beau blue',
    'Beaver',
    'Beige',
    'Bisque',
    'Bistre',
    'Bittersweet',
    'Black',
    'Blanched Almond',
    'Bleu de France',
    'Blizzard Blue',
    'Blond',
    'Blue',
    'Blue Bell',
    'Blue Gray',
    'Blue green',
    'Blue purple',
    'Blue violet',
    'Blush',
    'Bole',
    'Bondi blue',
    'Bone',
    'Boston University Red',
    'Bottle green',
    'Boysenberry',
    'Brandeis blue',
    'Brass',
    'Brick red',
    'Bright cerulean',
    'Bright green',
    'Bright lavender',
    'Bright maroon',
    'Bright pink',
    'Bright turquoise',
    'Bright ube',
    'Brilliant lavender',
    'Brilliant rose',
    'Brink pink',
    'British racing green',
    'Bronze',
    'Brown',
    'Bubble gum',
    'Bubbles',
    'Buff',
    'Bulgarian rose',
    'Burgundy',
    'Burlywood',
    'Burnt orange',
    'Burnt sienna',
    'Burnt umber',
    'Byzantine',
    'Byzantium',
    'CG Blue',
    'CG Red',
    'Cadet',
    'Cadet blue',
    'Cadet grey',
    'Cadmium green',
    'Cadmium orange',
    'Cadmium red',
    'Cadmium yellow',
    'Café au lait',
    'Café noir',
    'Cal Poly Pomona green',
    'Cambridge Blue',
    'Camel',
    'Camouflage green',
    'Canary',
    'Canary yellow',
    'Candy apple red',
    'Candy pink',
    'Capri',
    'Caput mortuum',
    'Cardinal',
    'Caribbean green',
    'Carmine',
    'Carmine pink',
    'Carmine red',
    'Carnation pink',
    'Carnelian',
    'Carolina blue',
    'Carrot orange',
    'Celadon',
    'Celeste',
    'Celestial blue',
    'Cerise',
    'Cerise pink',
    'Cerulean',
    'Cerulean blue',
    'Chamoisee',
    'Champagne',
    'Charcoal',
    'Chartreuse',
    'Cherry',
    'Cherry blossom pink',
    'Chestnut',
    'Chocolate',
    'Chrome yellow',
    'Cinereous',
    'Cinnabar',
    'Cinnamon',
    'Citrine',
    'Classic rose',
    'Cobalt',
    'Cocoa brown',
    'Coffee',
    'Columbia blue',
    'Cool black',
    'Cool grey',
    'Copper',
    'Copper rose',
    'Coquelicot',
    'Coral',
    'Coral pink',
    'Coral red',
    'Cordovan',
    'Corn',
    'Cornell Red',
    'Cornflower',
    'Cornflower blue',
    'Cornsilk',
    'Cosmic latte',
    'Cotton candy',
    'Cream',
    'Crimson',
    'Crimson Red',
    'Crimson glory',
    'Cyan',
    'Daffodil',
    'Dandelion',
    'Dark blue',
    'Dark brown',
    'Dark byzantium',
    'Dark candy apple red',
    'Dark cerulean',
    'Dark chestnut',
    'Dark coral',
    'Dark cyan',
    'Dark electric blue',
    'Dark goldenrod',
    'Dark gray',
    'Dark green',
    'Dark jungle green',
    'Dark khaki',
    'Dark lava',
    'Dark lavender',
    'Dark magenta',
    'Dark midnight blue',
    'Dark olive green',
    'Dark orange',
    'Dark orchid',
    'Dark pastel blue',
    'Dark pastel green',
    'Dark pastel purple',
    'Dark pastel red',
    'Dark pink',
    'Dark powder blue',
    'Dark raspberry',
    'Dark red',
    'Dark salmon',
    'Dark scarlet',
    'Dark sea green',
    'Dark sienna',
    'Dark slate blue',
    'Dark slate gray',
    'Dark spring green',
    'Dark tan',
    'Dark tangerine',
    'Dark taupe',
    'Dark terra cotta',
    'Dark turquoise',
    'Dark violet',
    'Dartmouth green',
    'Davy grey',
    'Debian red',
    'Deep carmine',
    'Deep carmine pink',
    'Deep carrot orange',
    'Deep cerise',
    'Deep champagne',
    'Deep chestnut',
    'Deep coffee',
    'Deep fuchsia',
    'Deep jungle green',
    'Deep lilac',
    'Deep magenta',
    'Deep peach',
    'Deep pink',
    'Deep saffron',
    'Deep sky blue',
    'Denim',
    'Desert',
    'Desert sand',
    'Dim gray',
    'Dodger blue',
    'Dogwood rose',
    'Dollar bill',
    'Drab',
    'Duke blue',
    'Earth yellow',
    'Ecru',
    'Eggplant',
    'Eggshell',
    'Egyptian blue',
    'Electric blue',
    'Electric crimson',
    'Electric cyan',
    'Electric green',
    'Electric indigo',
    'Electric lavender',
    'Electric lime',
    'Electric purple',
    'Electric ultramarine',
    'Electric violet',
    'Electric yellow',
    'Emerald',
    'Eton blue',
    'Fallow',
    'Falu red',
    'Famous',
    'Fandango',
    'Fashion fuchsia',
    'Fawn',
    'Feldgrau',
    'Fern',
    'Fern green',
    'Ferrari Red',
    'Field drab',
    'Fire engine red',
    'Firebrick',
    'Flame',
    'Flamingo pink',
    'Flavescent',
    'Flax',
    'Floral white',
    'Fluorescent orange',
    'Fluorescent pink',
    'Fluorescent yellow',
    'Folly',
    'Forest green',
    'French beige',
    'French blue',
    'French lilac',
    'French rose',
    'Fuchsia',
    'Fuchsia pink',
    'Fulvous',
    'Fuzzy Wuzzy',
    'Gainsboro',
    'Gamboge',
    'Ghost white',
    'Ginger',
    'Glaucous',
    'Glitter',
    'Gold',
    'Golden brown',
    'Golden poppy',
    'Golden yellow',
    'Goldenrod',
    'Granny Smith Apple',
    'Gray',
    'Gray asparagus',
    'Green',
    'Green Blue',
    'Green yellow',
    'Grullo',
    'Guppie green',
    'Halayà úbe',
    'Han blue',
    'Han purple',
    'Hansa yellow',
    'Harlequin',
    'Harvard crimson',
    'Harvest Gold',
    'Heart Gold',
    'Heliotrope',
    'Hollywood cerise',
    'Honeydew',
    'Hooker green',
    'Hot magenta',
    'Hot pink',
    'Hunter green',
    'Icterine',
    'Inchworm',
    'India green',
    'Indian red',
    'Indian yellow',
    'Indigo',
    'International Klein Blue',
    'International orange',
    'Iris',
    'Isabelline',
    'Islamic green',
    'Ivory',
    'Jade',
    'Jasmine',
    'Jasper',
    'Jazzberry jam',
    'Jonquil',
    'June bud',
    'Jungle green',
    'KU Crimson',
    'Kelly green',
    'Khaki',
    'La Salle Green',
    'Languid lavender',
    'Lapis lazuli',
    'Laser Lemon',
    'Laurel green',
    'Lava',
    'Lavender',
    'Lavender blue',
    'Lavender blush',
    'Lavender gray',
    'Lavender indigo',
    'Lavender magenta',
    'Lavender mist',
    'Lavender pink',
    'Lavender purple',
    'Lavender rose',
    'Lawn green',
    'Lemon',
    'Lemon Yellow',
    'Lemon chiffon',
    'Lemon lime',
    'Light Crimson',
    'Light Thulian pink',
    'Light apricot',
    'Light blue',
    'Light brown',
    'Light carmine pink',
    'Light coral',
    'Light cornflower blue',
    'Light cyan',
    'Light fuchsia pink',
    'Light goldenrod yellow',
    'Light gray',
    'Light green',
    'Light khaki',
    'Light pastel purple',
    'Light pink',
    'Light salmon',
    'Light salmon pink',
    'Light sea green',
    'Light sky blue',
    'Light slate gray',
    'Light taupe',
    'Light yellow',
    'Lilac',
    'Lime',
    'Lime green',
    'Lincoln green',
    'Linen',
    'Lion',
    'Liver',
    'Lust',
    'MSU Green',
    'Macaroni and Cheese',
    'Magenta',
    'Magic mint',
    'Magnolia',
    'Mahogany',
    'Maize',
    'Majorelle Blue',
    'Malachite',
    'Manatee',
    'Mango Tango',
    'Mantis',
    'Maroon',
    'Mauve',
    'Mauve taupe',
    'Mauvelous',
    'Maya blue',
    'Meat brown',
    'Medium Persian blue',
    'Medium aquamarine',
    'Medium blue',
    'Medium candy apple red',
    'Medium carmine',
    'Medium champagne',
    'Medium electric blue',
    'Medium jungle green',
    'Medium lavender magenta',
    'Medium orchid',
    'Medium purple',
    'Medium red violet',
    'Medium sea green',
    'Medium slate blue',
    'Medium spring bud',
    'Medium spring green',
    'Medium taupe',
    'Medium teal blue',
    'Medium turquoise',
    'Medium violet red',
    'Melon',
    'Midnight blue',
    'Midnight green',
    'Mikado yellow',
    'Mint',
    'Mint cream',
    'Mint green',
    'Misty rose',
    'Moccasin',
    'Mode beige',
    'Moonstone blue',
    'Mordant red 19',
    'Moss green',
    'Mountain Meadow',
    'Mountbatten pink',
    'Mulberry',
    'Munsell',
    'Mustard',
    'Myrtle',
    'Nadeshiko pink',
    'Napier green',
    'Naples yellow',
    'Navajo white',
    'Navy blue',
    'Neon Carrot',
    'Neon fuchsia',
    'Neon green',
    'Non-photo blue',
    'North Texas Green',
    'Ocean Boat Blue',
    'Ochre',
    'Office green',
    'Old gold',
    'Old lace',
    'Old lavender',
    'Old mauve',
    'Old rose',
    'Olive',
    'Olive Drab',
    'Olive Green',
    'Olivine',
    'Onyx',
    'Opera mauve',
    'Orange',
    'Orange Yellow',
    'Orange peel',
    'Orange red',
    'Orchid',
    'Otter brown',
    'Outer Space',
    'Outrageous Orange',
    'Oxford Blue',
    'Pacific Blue',
    'Pakistan green',
    'Palatinate blue',
    'Palatinate purple',
    'Pale aqua',
    'Pale blue',
    'Pale brown',
    'Pale carmine',
    'Pale cerulean',
    'Pale chestnut',
    'Pale copper',
    'Pale cornflower blue',
    'Pale gold',
    'Pale goldenrod',
    'Pale green',
    'Pale lavender',
    'Pale magenta',
    'Pale pink',
    'Pale plum',
    'Pale red violet',
    'Pale robin egg blue',
    'Pale silver',
    'Pale spring bud',
    'Pale taupe',
    'Pale violet red',
    'Pansy purple',
    'Papaya whip',
    'Paris Green',
    'Pastel blue',
    'Pastel brown',
    'Pastel gray',
    'Pastel green',
    'Pastel magenta',
    'Pastel orange',
    'Pastel pink',
    'Pastel purple',
    'Pastel red',
    'Pastel violet',
    'Pastel yellow',
    'Patriarch',
    'Payne grey',
    'Peach',
    'Peach puff',
    'Peach yellow',
    'Pear',
    'Pearl',
    'Pearl Aqua',
    'Peridot',
    'Periwinkle',
    'Persian blue',
    'Persian indigo',
    'Persian orange',
    'Persian pink',
    'Persian plum',
    'Persian red',
    'Persian rose',
    'Phlox',
    'Phthalo blue',
    'Phthalo green',
    'Piggy pink',
    'Pine green',
    'Pink',
    'Pink Flamingo',
    'Pink Sherbet',
    'Pink pearl',
    'Pistachio',
    'Platinum',
    'Plum',
    'Portland Orange',
    'Powder blue',
    'Princeton orange',
    'Prussian blue',
    'Psychedelic purple',
    'Puce',
    'Pumpkin',
    'Purple',
    'Purple Heart',
    "Purple Mountain's Majesty",
    'Purple mountain majesty',
    'Purple pizzazz',
    'Purple taupe',
    'Rackley',
    'Radical Red',
    'Raspberry',
    'Raspberry glace',
    'Raspberry pink',
    'Raspberry rose',
    'Raw Sienna',
    'Razzle dazzle rose',
    'Razzmatazz',
    'Red',
    'Red Orange',
    'Red brown',
    'Red violet',
    'Rich black',
    'Rich carmine',
    'Rich electric blue',
    'Rich lilac',
    'Rich maroon',
    'Rifle green',
    "Robin's Egg Blue",
    'Rose',
    'Rose bonbon',
    'Rose ebony',
    'Rose gold',
    'Rose madder',
    'Rose pink',
    'Rose quartz',
    'Rose taupe',
    'Rose vale',
    'Rosewood',
    'Rosso corsa',
    'Rosy brown',
    'Royal azure',
    'Royal blue',
    'Royal fuchsia',
    'Royal purple',
    'Ruby',
    'Ruddy',
    'Ruddy brown',
    'Ruddy pink',
    'Rufous',
    'Russet',
    'Rust',
    'Sacramento State green',
    'Saddle brown',
    'Safety orange',
    'Saffron',
    'Saint Patrick Blue',
    'Salmon',
    'Salmon pink',
    'Sand',
    'Sand dune',
    'Sandstorm',
    'Sandy brown',
    'Sandy taupe',
    'Sap green',
    'Sapphire',
    'Satin sheen gold',
    'Scarlet',
    'School bus yellow',
    'Screamin Green',
    'Sea blue',
    'Sea green',
    'Seal brown',
    'Seashell',
    'Selective yellow',
    'Sepia',
    'Shadow',
    'Shamrock',
    'Shamrock green',
    'Shocking pink',
    'Sienna',
    'Silver',
    'Sinopia',
    'Skobeloff',
    'Sky blue',
    'Sky magenta',
    'Slate blue',
    'Slate gray',
    'Smalt',
    'Smokey topaz',
    'Smoky black',
    'Snow',
    'Spiro Disco Ball',
    'Spring bud',
    'Spring green',
    'Steel blue',
    'Stil de grain yellow',
    'Stizza',
    'Stormcloud',
    'Straw',
    'Sunglow',
    'Sunset',
    'Sunset Orange',
    'Tan',
    'Tangelo',
    'Tangerine',
    'Tangerine yellow',
    'Taupe',
    'Taupe gray',
    'Tawny',
    'Tea green',
    'Tea rose',
    'Teal',
    'Teal blue',
    'Teal green',
    'Terra cotta',
    'Thistle',
    'Thulian pink',
    'Tickle Me Pink',
    'Tiffany Blue',
    'Tiger eye',
    'Timberwolf',
    'Titanium yellow',
    'Tomato',
    'Toolbox',
    'Topaz',
    'Tractor red',
    'Trolley Grey',
    'Tropical rain forest',
    'True Blue',
    'Tufts Blue',
    'Tumbleweed',
    'Turkish rose',
    'Turquoise',
    'Turquoise blue',
    'Turquoise green',
    'Tuscan red',
    'Twilight lavender',
    'Tyrian purple',
    'UA blue',
    'UA red',
    'UCLA Blue',
    'UCLA Gold',
    'UFO Green',
    'UP Forest green',
    'UP Maroon',
    'USC Cardinal',
    'USC Gold',
    'Ube',
    'Ultra pink',
    'Ultramarine',
    'Ultramarine blue',
    'Umber',
    'United Nations blue',
    'University of California Gold',
    'Unmellow Yellow',
    'Upsdell red',
    'Urobilin',
    'Utah Crimson',
    'Vanilla',
    'Vegas gold',
    'Venetian red',
    'Verdigris',
    'Vermilion',
    'Veronica',
    'Violet',
    'Violet Blue',
    'Violet Red',
    'Viridian',
    'Vivid auburn',
    'Vivid burgundy',
    'Vivid cerise',
    'Vivid tangerine',
    'Vivid violet',
    'Warm black',
    'Waterspout',
    'Wenge',
    'Wheat',
    'White',
    'White smoke',
    'Wild Strawberry',
    'Wild Watermelon',
    'Wild blue yonder',
    'Wine',
    'Wisteria',
    'Xanadu',
    'Yale Blue',
    'Yellow',
    'Yellow Orange',
    'Yellow green',
    'Zaffre',
    'Zinnwaldite brown',
    'Multicolor',
]

VALID_FABRICS = [
    'Alpaca',
    'Angora',
    'Bamboo Fabric',
    'Batiste',
    'Brocade',
    'Burlap',
    'Calico',
    'Cambric',
    'Canvas',
    'Cashmere',
    'Challis',
    'Chambray',
    'Chamois',
    'Chenille',
    'Chiffon',
    'Coolmax',
    'Corduroy',
    'Cotton',
    'Crepe',
    'Crêpon',
    'Crinoline',
    'Damask',
    'Denim',
    'Dupioni Silk',
    'Faille',
    'Flannel',
    'Fleece',
    'Gabardine',
    'Georgette',
    'Gingham',
    'Grosgrain',
    'Hemp',
    'Hessian (Burlap)',
    'Interlock Knit',
    'Jacquard',
    'Jersey',
    'Lace',
    'Leather',
    'Linen',
    'Lycra (Spandex)',
    'Merino Wool',
    'Microfiber',
    'Modal',
    'Moleskin',
    'Muslin',
    'Neoprene',
    'Organza',
    'Organza',
    'Ottoman',
    'Peau de Soie',
    'Percale',
    'Percale',
    'Piqué',
    'Polyester',
    'Ramie',
    'Rayon',
    'Ripstop',
    'Satin',
    'Seersucker',
    'Silk',
    'Spandex',
    'Suede',
    'Synthetic Fabrics',
    'Taffeta',
    'Tartan',
    'Tencel (Lyocell)',
    'Terrycloth',
    'Tulle',
    'Tweed',
    'Velour',
    'Velvet',
    'Velveteen',
    'Vinyl',
    'Wool'
]